---
name: Locale-Maketext-TieHash-L10N
version: 0.06
author:
  - 'Steffen Winkler <steffenw@cpan.org>'
abstract: Tying language handle to a hash
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Params::Validate: 0
build_requires:
  Locale::Maketext: 1.06
  Test::More: 0
provides:
  Locale::Maketext::TieHash::L10N:
    file: lib/Locale/Maketext/TieHash/L10N.pm
    version: 0.06
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
