# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Locale-Maketext-TieHash-L10N
version:      0.01
version_from: lib/Locale/Maketext/TieHash/L10N.pm
installdirs:  site
requires:
    Locale::Maketext:              1.06
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
