---
name: Locale-Maketext-TieHash-L10N
version: 0.09
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'Locale::Maketext::TieHash::L10N - Tying language handle to a hash'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Params::Validate: 0
build_requires:
  Locale::Maketext: 1.06
  Test::Simple: 0
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Locale::Maketext::TieHash::L10N:
    file: lib/Locale/Maketext/TieHash/L10N.pm
    version: 0.09
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
